services:
  learn-nestjs-api:
    image: learn-nestjs-api-local
    container_name: learn-nestjs-api-local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/main.js
    env_file:
      - .env
    ports:
      - '${APP_PORT}:5555'
    volumes:
      - ./src:/app/src
    networks:
      - learn-nestjs-network

  db:
    image: mysql
    container_name: learn-nestjs-mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - learn-nestjs-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '${REDIS_PASSWORD}'
    networks:
      - learn-nestjs-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - learn-nestjs-network

volumes:
  mysql_data:
  redis_data:

networks:
  learn-nestjs-network:
    driver: bridge
