name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  - push:
      branches:
        - main

  jobs: 
    name: Build
      build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: ['20.18.0']
        steps:
          - name: Checkout code
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4 
            with:
                node-version: ${{ matrix.node-version }}
          - name: Install dependencies
            run: npm install -g pnpm && pnpm install
          - name: Build
            run: pnpm run build

