name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - name: Build docker images
        run: docker build --platform linux/amd64 -t hoangday185/nestjs:v0 .
      - name: Login docker hub
        run: docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_PASSWORD}}"
      - name: Push docker images
        run: docker push hoangday185/nestjs:v0
